### ISSUE TITLE
run exe file turn on error as below pic

### ISSUE THREAD

**Issue by zhouxs1023** [jpickrell/imgui#1]
I use win7 x64+vs2015 compile imgui-master,compiler successfully,but run exe file turn on error
![qq 20180605213246](https://user-images.githubusercontent.com/905931/40979337-1f1e6e08-6908-11e8-8101-9bf28919f44f.png)

**Comment by jpickrell** [comment]
That was probably because I didn't have the fonts included.  They're part of the repository now, so running the example should be easier.

**Comment by zhouxs1023** [comment]
Tks, exe file had been successfully run
